---
title: "Data Tidying"
author: "Jillian Burns"
date: "11/6/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, warning = F, message = F}
library(dplyr)
library(tidyr)
```



# Red and Clean Data 

```{r}
catch_original <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_original)
```

Remove `all` column and `notes` column because we don't need them. Can also use select to re order columns. 

```{r}
catch_data <- catch_original %>% 
  #select(Region, Year, Chinook, Sockeye, Coho, Pink, Chum)
  select(-All, -notesRegCode)

head(catch_data)
```


```{r}
summary(catch_data)
```

## Fix Chinook Column

Use `mutate` to fix Chinook column

```{r}
catch_clean <- catch_data %>% 
  mutate(Chinook = if.else(Chinook == "I", 1, Chinook)) %>% 
  mutate(Chinook = as.numeric(Chinook))


```


Finding the rows that got tunred into NA

```{r}
i <- which(is.na(catch_clean$Chinook))
i
```

```{r}
catch_original[i,]
```

# Reshape Data

```{r}
catch_long <- catch_clean %>% 
  pivot_longer(cols = -c(Region, Year),
               names_to = "species",
               values_to = "count")

head(catch_long)
```


# Summarize Data

# Join to Reion Table

